apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: healthcare
  namespace: default
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: health-workload-01
  namespace: default
spec:
  project: healthcare
  source:
    repoURL: 'https://github.com/msfidelis/nutrition-overengineering.git'
    targetRevision: HEAD
    path: samples/istio
  destination:
    name: eks-shard-1
  syncPolicy:
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: health-workload-02
  namespace: default
spec:
  project: healthcare
  source:
    repoURL: 'https://github.com/msfidelis/nutrition-overengineering.git'
    targetRevision: HEAD
    path: samples/istio
  destination:
    name: eks-shard-2
  syncPolicy:
    automated: {}