---
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: example-policy
spec:
  resourceSelectors:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: guestbooks.webapp.my.domain
  placement:
    clusterAffinity:
      clusterNames:
        - member1

---
apiVersion: cluster.karmada.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    displayName: cluster-01
  name: cluster-01
  namespace: karmada-system
spec:
  syncMode: Pull
  apiEndpoint: //CF3A52EFCA2AADF925DD3B986B2AC8D9.yl4.us-east-1.eks.amazonaws.com
  secretRef:
    # Update as needed
    namespace: karmada-system
    name: cluster-01-kubeconfig
  # Update as needed
  provider: aws
  region: us-east-1